# config/component_params.yml
# Parameters for components used across scenarios, unless overridden

# Grid Connection Parameters
grid:
  capacity_mw: 10.0 #
  import_cost_eur_per_mwh: 50.0
  export_price_eur_per_mwh: 20.0 
  transformer_efficiency: 0.98

# Baseline Assets
baseline_pv:
  capacity_kw: 15.0
  marginal_cost: 0

#baseline_heat_source:
 # type: gas_boiler # or 'district_heating_import' 
  #capacity_mw_th: 0.05
  #cost_eur_per_mwh_th: 50.0 
  #efficiency_if_boiler: 0.9 # Not used if DH import

# Placeholder load parameters
social_building:
  electricity_load_profile: Social_Building_Loads.csv
  pv_generation_profile: Solar_PV_Generation.csv
  heat_demand_profile: Social_Building_Loads.csv
  heat_source: boiler
  #in the future I can add heat_source: district_heating

# Add sections for other components used in different scenarios:
# battery_storage:
#   charge_efficiency: 0.95
#   discharge_efficiency: 0.95
#   capital_cost_eur_per_kw: 300 # For investment optimisation
#   capital_cost_eur_per_kwh: 150 # For investment optimisation

# thermal_storage:
#   loss_rate_percent_per_hour: 0.1
#   capital_cost_eur_per_kwh: 10 # For investment optimisation

# heat_pump:
#   efficiency_cop: 3.5 # Coefficient of Performance
#   capital_cost_eur_per_kw_th: 400 # For investment optimisation
