# config/component_params.yml
# Parameters for components used across scenarios, unless overridden

# Grid Connection Parameters
grid:
  capacity_mw: 10.0 # !! ADJUST !!
  import_cost_eur_per_mwh: 50.0 # !! ADJUST !!
  export_price_eur_per_mwh: 20.0 # !! ADJUST !!
  transformer_efficiency: 0.98

# Baseline Assets
baseline_pv:
  capacity_kw: 50.0 # !! ADJUST based on existing PV !!
  # Profile loaded from data/input/timeseries/solar_pv_generation.csv
  marginal_cost: 0

baseline_heat_source:
  type: gas_boiler # or 'district_heating_import' - !! ADJUST !!
  capacity_mw_th: 5.0 # !! ADJUST !!
  cost_eur_per_mwh_th: 40.0 # !! ADJUST !!
  efficiency_if_boiler: 0.9 # Not used if DH import

# Placeholder load parameters (adjust or define in main config if preferred)
loads:
  stadium_elec_peak_mw: 0.5 # !! ADJUST !!
  stadium_heat_peak_mw: 0.8 # !! ADJUST !!
  pool_elec_peak_mw: 0.3 # !! ADJUST !!
  pool_heat_peak_mw: 1.0 # !! ADJUST !! Pool heat might be constant
  general_elec_peak_mw: 1.5 # !! ADJUST !!
  general_heat_peak_mw: 2.0 # !! ADJUST !!

# High PV Scenario Assets
high_pv:
  # Stadium rooftop PV
  stadium_pv_capacity_kw: 200.0  # Assuming 200 kW of PV on stadium roof
  # Swimming pool rooftop PV
  pool_pv_capacity_kw: 150.0     # Assuming 150 kW of PV on pool roof
  # General district PV (e.g., on other buildings, carports)
  general_pv_capacity_kw: 300.0  # Assuming 300 kW of PV on other surfaces
  # All PV installations use the same generation profile
  # Profile loaded from data/input/timeseries/solar_pv_generation.csv
  marginal_cost: 0

# Add sections for other components used in different scenarios:
# battery_storage:
#   charge_efficiency: 0.95
#   discharge_efficiency: 0.95
#   capital_cost_eur_per_kw: 300 # For investment optimisation
#   capital_cost_eur_per_kwh: 150 # For investment optimisation

# thermal_storage:
#   loss_rate_percent_per_hour: 0.1
#   capital_cost_eur_per_kwh: 10 # For investment optimisation

# heat_pump:
#   efficiency_cop: 3.5 # Coefficient of Performance
#   capital_cost_eur_per_kw_th: 400 # For investment optimisation
